version: '2'
services:
  main-service: 
    build: ./main-service/
    container_name: php_apache-container
    ports: 
      - 800:80
    volumes:
      - ./main-service/www/html/:/var/www/html/
    links:
      - mysql

  mysql:  
    image: mysql:latest
    container_name: mysql-container
    volumes_from:
      - mysql-data
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: zavrel_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password

  mysql-data:  
    image: mysql:latest
    container_name: mysql-data-container
    volumes:
      - /var/lib/mysql
    command: "true"

  phpmyadmin:  
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-container
    ports:
      - 8080:80
    links:
      - mysql
    environment:
      PMA_HOST: mysql
